// Mock data used when the database is unavailable (DB not yet configured)

export const MOCK_SERVICES = [
  {
    id: "mock-1",
    nameRu: "Терапия",
    nameTj: "Табобат",
    descriptionRu: "Диагностика и лечение заболеваний внутренних органов. Комплексный осмотр пациента.",
    descriptionTj: "Ташхис ва табобати бемориҳои узвҳои дохилӣ.",
    durationMin: 30,
    price: 150,
    iconName: "default",
    _count: { doctors: 2 },
  },
  {
    id: "mock-2",
    nameRu: "Кардиология",
    nameTj: "Кардиология",
    descriptionRu: "Диагностика и лечение заболеваний сердца и сосудов. ЭКГ, УЗИ сердца.",
    descriptionTj: "Ташхис ва табобати бемориҳои дил ва рагҳо.",
    durationMin: 45,
    price: 250,
    iconName: "heart",
    _count: { doctors: 1 },
  },
  {
    id: "mock-3",
    nameRu: "Неврология",
    nameTj: "Неврология",
    descriptionRu: "Диагностика и лечение заболеваний нервной системы. Головные боли, невриты.",
    descriptionTj: "Ташхис ва табобати бемориҳои системаи асаб.",
    durationMin: 40,
    price: 200,
    iconName: "brain",
    _count: { doctors: 1 },
  },
  {
    id: "mock-4",
    nameRu: "Офтальмология",
    nameTj: "Офтальмология",
    descriptionRu: "Проверка зрения, подбор очков и линз. Лечение глазных заболеваний.",
    descriptionTj: "Санҷиши биноӣ ва табобати бемориҳои чашм.",
    durationMin: 30,
    price: 180,
    iconName: "eye",
    _count: { doctors: 1 },
  },
  {
    id: "mock-5",
    nameRu: "Лабораторная диагностика",
    nameTj: "Ташхиси лаборатория",
    descriptionRu: "Анализы крови, мочи, биохимия. Быстрый результат в течение 24 часов.",
    descriptionTj: "Таҳлили хун, пешоб, биохимия.",
    durationMin: 15,
    price: 80,
    iconName: "lab",
    _count: { doctors: 2 },
  },
  {
    id: "mock-6",
    nameRu: "Хирургия",
    nameTj: "Ҷарроҳӣ",
    descriptionRu: "Малоинвазивные хирургические вмешательства. Удаление новообразований.",
    descriptionTj: "Амалиётҳои ҷарроҳии хурд.",
    durationMin: 60,
    price: 500,
    iconName: "default",
    _count: { doctors: 1 },
  },
];

export const MOCK_DOCTORS = [
  {
    id: "mock-doc-1",
    nameRu: "Алиев Бахром Содикович",
    nameTj: "Алиев Баҳром Содиқович",
    specialtyRu: "Терапевт",
    specialtyTj: "Терапевт",
    photoUrl: null,
    workDays: [1, 2, 3, 4, 5],
    workStart: "09:00",
    workEnd: "17:00",
  },
  {
    id: "mock-doc-2",
    nameRu: "Рахимова Зарина Камолевна",
    nameTj: "Раҳимова Зарина Камолевна",
    specialtyRu: "Кардиолог",
    specialtyTj: "Кардиолог",
    photoUrl: null,
    workDays: [1, 2, 3, 4, 5],
    workStart: "08:00",
    workEnd: "16:00",
  },
  {
    id: "mock-doc-3",
    nameRu: "Исмоилов Давлат Хасанович",
    nameTj: "Исмоилов Давлат Ҳасанович",
    specialtyRu: "Невролог",
    specialtyTj: "Невролог",
    photoUrl: null,
    workDays: [1, 3, 5],
    workStart: "10:00",
    workEnd: "18:00",
  },
  {
    id: "mock-doc-4",
    nameRu: "Каримова Мадина Юсуфовна",
    nameTj: "Каримова Мадина Юсуфовна",
    specialtyRu: "Офтальмолог",
    specialtyTj: "Офтальмолог",
    photoUrl: null,
    workDays: [2, 4],
    workStart: "09:00",
    workEnd: "15:00",
  },
];
